#pragma once

namespace OBJ
{
	enum ID {BLOCK, ENEMY, NPC, PROP, PLAYER, BULLET,  END};
}

namespace BULLET
{
	enum ID {PISTOL, HEAVY, ROCKET, SHOTGUN, ENEMYBULLET, SOLDAEROOT,SARUBIA,BAZUKA,DICOKKA,IRONLIZARD, END};
}

namespace VEHICLE
{
	enum ID {TANK, END};
}

namespace NPC
{
	enum ID {SLAVE, TRAVELER, END};
}

namespace ITEM
{
	enum ID {WEAPON,AMMO,GRENADE,LIFE,ITEMBOX,END};
}

namespace ENEMY
{
	enum ID {SOLDIER,ARABIAN,THREEHEAD,MASKNELL,SOLDAE,SARUBIA,BAZUKA,DICOKKA, END};
}

namespace BLOCK
{
	enum ID {CAR,END};
}

namespace SCENE
{
	enum ID {TITLE,MENU,GAME,GAME1,END};
}

namespace DIR
{
	enum ID {UP,DOWN,LEFT,RIGHT,UP_RIGHT,UP_LEFT,DOWN_RIGHT,DOWN_LEFT,END};
}

namespace WEAPON
{
	enum ID {PISTOL, HEAVY, ROCKET, SHOTGUN, LASER, IRONLIZARD,END};
}

namespace ACTION
{
	enum ID {IDLE, MOVE, JUMP, FIRE, STAB, GRENADE, DIE, END };
	
}

namespace ANIM
{
	enum PLAYER { PLAYER_IDLE, PLAYER_MOVE, PLAYER_FIRE,
		PLAYER_UP, PLAYER_STAB, PLAYER_GRENADE, PLAYER_DIE,
		PLAYER_JUMP, PLAYER_JUMP_UP, PLAYER_JUMP_DOWN, PLAYER_JUMP_FIRE,
		PLAYER_DOWN, PLAYER_DOWN_FIRE, PLAYER_END };

	enum ITEM {
		AMMO,GRENADE,LIFE,HEAVY,ROCKET,ITEM_END
	};
}

namespace SOLDIER
{
	enum CLASS { PRIVATE, SERGENT , END };
}

namespace THREEHEAD
{
	enum HEAD {LEFT,MID,RIGHT};
	enum STATE { NONE, DOOR_OPEN, CURTAIN_OPEN, ATTACK, DESTORY };
}

namespace SOLDAE
{
	enum STATE{IDLE, LASER, SUNSHINE, ROOT, DIE};
}